// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	FetchResponse(ctx context.Context, in *FetchResponseRequest, opts ...grpc.CallOption) (ProductService_FetchResponseClient, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) FetchResponse(ctx context.Context, in *FetchResponseRequest, opts ...grpc.CallOption) (ProductService_FetchResponseClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProductService_ServiceDesc.Streams[0], "/trple.product.v1.ProductService/FetchResponse", opts...)
	if err != nil {
		return nil, err
	}
	x := &productServiceFetchResponseClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProductService_FetchResponseClient interface {
	Recv() (*FetchResponseResponse, error)
	grpc.ClientStream
}

type productServiceFetchResponseClient struct {
	grpc.ClientStream
}

func (x *productServiceFetchResponseClient) Recv() (*FetchResponseResponse, error) {
	m := new(FetchResponseResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations should embed UnimplementedProductServiceServer
// for forward compatibility
type ProductServiceServer interface {
	FetchResponse(*FetchResponseRequest, ProductService_FetchResponseServer) error
}

// UnimplementedProductServiceServer should be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (UnimplementedProductServiceServer) FetchResponse(*FetchResponseRequest, ProductService_FetchResponseServer) error {
	return status.Errorf(codes.Unimplemented, "method FetchResponse not implemented")
}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_FetchResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchResponseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductServiceServer).FetchResponse(m, &productServiceFetchResponseServer{stream})
}

type ProductService_FetchResponseServer interface {
	Send(*FetchResponseResponse) error
	grpc.ServerStream
}

type productServiceFetchResponseServer struct {
	grpc.ServerStream
}

func (x *productServiceFetchResponseServer) Send(m *FetchResponseResponse) error {
	return x.ServerStream.SendMsg(m)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trple.product.v1.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchResponse",
			Handler:       _ProductService_FetchResponse_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "product/v1/product.proto",
}
